#!/bin/bash

set -e

sleep 20 # Wait till everything is finished
clear
fdisk /dev/mmcblk0 <<EOF
d # Delete the first partition
n # Create a new partition for boot
p # A primary partition temporarily
1
8192
+68M
t # Set the type
c
n
p
2


w # Write it all
EOF
echo y | mkfs.fat -F 32 /dev/mmcblk0p1
echo y | mkfs.ext4 /dev/mmcblk0p2

/bin/mount /dev/mmcblk0p2 /mnt
mkdir /mnt/boot
/bin/mount -o umask=000 /dev/mmcblk0p1 /mnt/boot
/bin/mount /dev/sda1 /root

tar xpzkf /root/boot.tar.gz -C /mnt/boot/
tar xpzkf /root/root.tar.gz -C /mnt/

umount /mnt/boot
umount /mnt
umount /root

clear
echo "ALL DONE! PULL THE POWER AND BOOT AGAIN!"
